<?php

/**
 * PluginadHTMLWrapperSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    adHTMLWrapperSlotPlugin
 * @subpackage model
 * @author     Daniel Lohse <info@asapdesign.de>
 */
abstract class PluginadHTMLWrapperSlot extends BaseadHTMLWrapperSlot
{
  protected $editDefault = false;
}