<?php

/**
 * PluginadHTMLWrapperSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginadHTMLWrapperSlotTable extends aSlotTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginadHTMLWrapperSlotTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginadHTMLWrapperSlot');
  }
}
